# PowerShell script to set up fresh PostgreSQL migrations
# This handles the case where old MySQL migrations exist

Write-Host "Setting up fresh PostgreSQL migrations" -ForegroundColor Cyan
Write-Host ""

# Step 1: Backup old migrations
$migrationsDir = "prisma\migrations"
$backupDir = "prisma\migrations_mysql_backup"

if (Test-Path $migrationsDir) {
    Write-Host "Backing up old MySQL migrations..." -ForegroundColor Yellow
    if (Test-Path $backupDir) {
        Remove-Item $backupDir -Recurse -Force
    }
    New-Item -ItemType Directory -Path $backupDir | Out-Null
    Copy-Item "$migrationsDir\*" -Destination $backupDir -Recurse -Exclude "migration_lock.toml"
    Write-Host "Old migrations backed up to: $backupDir" -ForegroundColor Green
    Write-Host ""
}

# Step 2: Clear the migrations folder (keep only migration_lock.toml)
Write-Host "Clearing old migrations (keeping migration_lock.toml)..." -ForegroundColor Yellow
Get-ChildItem $migrationsDir -Directory | Where-Object { $_.Name -ne "migration_lock.toml" } | Remove-Item -Recurse -Force
Write-Host "Old migrations cleared" -ForegroundColor Green
Write-Host ""

# Step 3: Ensure migration_lock.toml is set to postgresql
$lockFile = "prisma\migrations\migration_lock.toml"
if (Test-Path $lockFile) {
    $lockContent = Get-Content $lockFile -Raw
    if ($lockContent -notmatch 'provider\s*=\s*"postgresql"') {
        $lockContent = $lockContent -replace 'provider\s*=\s*"[^"]+"', 'provider = "postgresql"'
        Set-Content -Path $lockFile -Value $lockContent
        Write-Host "Updated migration_lock.toml to postgresql" -ForegroundColor Green
    }
} else {
    $lockContent = @"
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
"@
    Set-Content -Path $lockFile -Value $lockContent
    Write-Host "Created migration_lock.toml" -ForegroundColor Green
}
Write-Host ""

# Step 4: Use db push to create schema (bypasses migration validation)
Write-Host "Pushing schema to PostgreSQL (this creates tables directly)..." -ForegroundColor Cyan
Write-Host ""

$pushResult = npx prisma db push --accept-data-loss 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "Schema pushed successfully!" -ForegroundColor Green
    Write-Host ""
    
    # Step 5: Create baseline migration
    Write-Host "Creating baseline migration..." -ForegroundColor Cyan
    Write-Host ""
    
    $migrateResult = npx prisma migrate dev --name init_postgresql --create-only 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Baseline migration created!" -ForegroundColor Green
        Write-Host ""
        Write-Host "Next steps:" -ForegroundColor Cyan
        Write-Host "1. Review the generated migration file" -ForegroundColor White
        Write-Host "2. Apply it: npx prisma migrate deploy" -ForegroundColor Yellow
        Write-Host "3. Migrate your data: npm run migrate:mysql-to-postgres" -ForegroundColor Yellow
    } else {
        Write-Host "Warning: Could not create migration (this is okay if schema is already applied)" -ForegroundColor Yellow
        Write-Host "You can now migrate your data: npm run migrate:mysql-to-postgres" -ForegroundColor Yellow
    }
} else {
    Write-Host "Error pushing schema:" -ForegroundColor Red
    Write-Host $pushResult
    Write-Host ""
    Write-Host "Alternative: Try using prisma migrate dev directly after fixing migrations" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Done!" -ForegroundColor Green

